baseURL = "https://imroc.io/"
languageCode = "zh-cn"
title = "roc"
theme = "xhugo"
DefaultContentLanguage = "en"
hasCJKLanguage = true
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
#googleAnalytics = "XXX"


[Params]
  hello = "Hi,I'm Roc"
  # subtitle = "I'm ROC"
  logo = "https://res.cloudinary.com/imroc/image/upload/v1521031841/avatar.png"
  favicon = "favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  description = "imroc.io|roc的博客|Cloud Native|Kubernetes|Go|Golang"

[Params.comments.github]
owner = "imroc" # github account
repo = "imroc.github.io" # the repo in your github account which comments data would be submitted into it's issue
# client_id and client_secret could be created by: Settings-Developer settings-OAuth Apps-New OAuth app
client_id = "d05b8f959b3111c6fb63"
client_secret = "f30ef76ea0050ed731ace76f7fbf684ae5d28fbc"

[[Params.bigimg]]
src = "https://res.cloudinary.com/imroc/image/upload/v1515849754/blog/banner/hacker.jpg"
desc = "Hacker"

[[Params.bigimg]]
src = "https://res.cloudinary.com/imroc/image/upload/v1515849764/blog/banner/kubernetes.png"
desc = "Kubernetes"

[[Params.bigimg]]
src = "http://res.cloudinary.com/imroc/image/upload/v1515849756/blog/banner/cloud_computing.jpg"
desc = "Cloud Computing"

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 1
    
[[menu.main]]
    parent = "Categories"
    name = "kubernetes"
    url = "categories/kubernetes"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "docker"
    url = "categories/docker"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "golang"
    url = "categories/golang"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "架构"
    url = "categories/arch"
    weight = 4

[[menu.main]]
    name = "Books"
    weight = 2

[[menu.main]]
    parent = "Books"
    name = "Kubernetes The Gradual Way"
    url = "kubernetes-the-gradual-way"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "About"
    url = "about"
    weight = 4


[Author]
  name = "roc"
  website = "imroc.io"
  email = "roc@imroc.io"
  github = "imroc"
  twitter = "imrocchan"
  # facebook = "username"
  # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  # gitlab = "username"
  # reddit = "username"
  # linkedin = "username"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"
